name: ci-cd

on:
  workflow_dispatch:
    inputs:
      environments:
        description: Environment to deploy
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore 'MyConsoleApp/MyConsoleApp.csproj'

      - name: Build
        run: dotnet build 'MyConsoleApp/MyConsoleApp.csproj' --no-restore

      - name: Publish
        run: dotnet publish 'MyConsoleApp/MyConsoleApp.csproj' -c Release -o ${{ github.workspace }}/artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-artifacts
          path: ${{ github.workspace }}/artifacts

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.environments }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-artifacts
          path: ./artifacts

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli

      - name: Sync files to S3
        run: |
          aws s3 sync ./artifacts s3://netbuckett --exclude ".git/*" --exclude ".github/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Replace with your AWS region
